version: '3.9'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "127.0.0.1:8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: oe%hiuth8Aghub5ein8a
    volumes:
      - ./website:/var/www/html
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: aeyieK{ura]n8jae0Uuw
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: oe%hiuth8Aghub5ein8a
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
