version: '3.9'

services:
  php-apache:
    container_name: apache
    build:
      context: ./php-apache
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./website:/var/www/html
    depends_on:
      - mysql
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - UPLOAD_LIMIT=64M
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: aeyieK{ura]n8jae0Uuw
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: oe%hiuth8Aghub5ein8a
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
